models:
  - type: main
    engine: openai
    model: llama3.2:1b
    parameters:
      base_url: "http://host.docker.internal:11434/v1"
      api_key: "dummy"

rails:
  input:
    flows:
      - self check input
  output:
    flows:
      - self check output
